version: "3.4"

services:
  bmusic-api:
    build: bmusic-api
    restart: "no"
    volumes:
      - ./bmusic-api/:/app
      - express_node_modules:/app/node_modules
    ports:
      - "4000:4000"
    env_file:
      - project.env

  bmusic-ui:
    build: bmusic-ui
    restart: "no"
    volumes:
      - ./bmusic-ui/:/app
      - angular_node_modules:/app/node_modules
    ports:
      - "4200:4200"

  # database:
  ##  image: postgres:latest
  #restart: "no"
  # volumes:
  #  - ./database_data:/var/lib/postgresql/data
  # env_file:
  # - project.env

volumes:
  database_data:
  angular_node_modules:
  express_node_modules:
