version: "3.4"

services:
  bmusic-api:
    build: bmusic-api
    restart: "no"
    volumes:
      - ./bmusic-api/:/app
      - express_node_modules:/app/node_modules
      - uploads_data:/app/data/uploads
      - covers_data:/app/data/covers
    ports:
      - "4000:4000"
    env_file:
      - project.env

  bmusic-ui:
    build: bmusic-ui
    restart: "no"
    volumes:
      - ./bmusic-ui/:/app
      - angular_node_modules:/app/node_modules
    ports:
      - "4200:4200"

  database:
    container_name: db-bmusic
    image: postgres:latest
    restart: "always"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/V1___initial_schema.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file:
      - project.env

volumes:
  database_data:
  uploads_data:
  covers_data:
  angular_node_modules:
  express_node_modules:
