version: "3.4"

services:
  bmusic-api:
    build:
      context: bmusic-api
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - project.env
    volumes:
      - uploads_data:/app/data/uploads
      - covers_data:/app/data/covers

  bmusic-ui:
    build:
      context: bmusic-ui
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "4200:4200"
    env_file:
      - project.env

  database:
    container_name: db-bmusic
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/V1___initial_schema.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file:
      - project.env

volumes:
  database_data:
  uploads_data:
  covers_data:
