version: "3.4"

services:
  bmusic-api:
    build: bmusic-api
    restart: "unless-stopped"
    volumes:
      - ./bmusic-api/:/app
      - express_node_modules:/app/node_modules
      - uploads_data:/app/data/uploads
      - covers_data:/app/data/covers
    ports:
      - "4000:4000"

  bmusic-ui:
    build: bmusic-ui
    restart: "unless-stopped"
    volumes:
      - ./bmusic-ui/:/app
      - angular_node_modules:/app/node_modules
    ports:
      - "4200:4200"

  database:
    container_name: db-bmusic
    image: postgres:latest
    restart: "unless-stopped"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db-bmusic
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/V1___initial_schema.sql:/docker-entrypoint-initdb.d/create_database.sql

volumes:
  database_data:
  uploads_data:
  covers_data:
  angular_node_modules:
  express_node_modules:
